// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
// /// // ...
//  await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
//  );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZUMXveSvj4QaSMnYVOIMS9GwfHXJp_Y',
    appId: '1:179462036772:web:3b13641acb2a9731a6a7b1',
    messagingSenderId: '179462036772',
    projectId: 'mybuggy-development',
    authDomain: 'mybuggy-development.firebaseapp.com',
    databaseURL: 'https://mybuggy-development-default-rtdb.firebaseio.com',
    storageBucket: 'mybuggy-development.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkReTKJCn5Z8rTxjybEldMD-ahKNfHvrc',
    appId: '1:179462036772:android:8eaa29f99ada7ccfa6a7b1',
    messagingSenderId: '179462036772',
    projectId: 'mybuggy-development',
    databaseURL: 'https://mybuggy-development-default-rtdb.firebaseio.com',
    storageBucket: 'mybuggy-development.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC2wNH4vWK4qusnt66vQoPIxtiWg_LsA0',
    appId: '1:179462036772:ios:303f00b49f9454cba6a7b1',
    messagingSenderId: '179462036772',
    projectId: 'mybuggy-development',
    databaseURL: 'https://mybuggy-development-default-rtdb.firebaseio.com',
    storageBucket: 'mybuggy-development.appspot.com',
    iosClientId: '179462036772-bqcrejerseliabvcjj7591m0h48vh6os.apps.googleusercontent.com',
    iosBundleId: 'com.example.passengerApp',
  );
}